/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/plan:generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_v1_projects__pid__plan_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Plan */
        patch: operations["edit_plan_api_v1_projects__pid__plan_patch"];
        trace?: never;
    };
    "/api/v1/projects/{pid}/plan:confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: operations["confirm_api_v1_projects__pid__plan_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/analysis:authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authorize Analysis */
        post: operations["authorize_analysis_api_v1_projects__pid__analysis_authorize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_v1_projects__pid__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/clips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clips */
        get: operations["clips_api_v1_projects__pid__clips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clips/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clip */
        get: operations["clip_api_v1_clips__cid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/clips/{cid}/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Membership */
        patch: operations["membership_api_v1_projects__pid__clips__cid__membership_patch"];
        trace?: never;
    };
    "/api/v1/jobs/{jid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_v1_jobs__jid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jid}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_v1_jobs__jid__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/renditions/{rid}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Content */
        get: operations["content_api_v1_renditions__rid__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_projects__pid__imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_api_v1_projects__pid__imports_post */
        Body_upload_api_v1_projects__pid__imports_post: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * Projection
             * @default unknown
             */
            projection: string;
            /** Files */
            files: string[];
        };
        /** Clip */
        Clip: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Group Key */
            group_key: string;
            /**
             * State
             * @enum {string}
             */
            state: "awaiting_ready" | "downloading" | "preparing" | "analyzing" | "analyzed" | "failed" | "blocked_format" | "excluded" | "queued";
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Generation
             * @default 1
             */
            generation: number;
            /** Rendition Id */
            rendition_id?: string | null;
            /** Duration */
            duration?: number | null;
            error?: components["schemas"]["ErrorDetail"] | null;
            /** Job Id */
            job_id?: string | null;
            /**
             * Source
             * @default local
             * @constant
             */
            source: "local";
            /** Size */
            size?: number | null;
            /** Sha256 */
            sha256?: string | null;
        };
        /** ClipPage */
        ClipPage: {
            /** Items */
            items: components["schemas"]["Clip"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** CreateProject */
        CreateProject: {
            /**
             * Model Upload Consent
             * @default false
             */
            model_upload_consent: boolean;
            /** Goal */
            goal: string;
            /**
             * Target Seconds
             * @default 45
             */
            target_seconds: number;
            /**
             * Conditions
             * @default
             */
            conditions: string;
        };
        /** Criterion */
        Criterion: {
            /** Id */
            id: string;
            /** Description */
            description: string;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /**
             * Continuous
             * @default false
             */
            continuous: boolean;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "DEVICE_DISCONNECTED" | "CAPABILITY_UNVERIFIED" | "CATALOG_INCOMPLETE" | "SCOPE_STALE" | "GROUP_NOT_READY" | "DOWNLOAD_INCOMPLETE" | "MEDIA_UNSUPPORTED" | "STORAGE_FULL" | "NETWORK_UNAVAILABLE" | "MODEL_TIMEOUT" | "MODEL_UPLOAD_NOT_AUTHORIZED" | "MODEL_OUTPUT_INVALID" | "STALE_REVISION" | "CONFLICT" | "NOT_FOUND" | "INVALID_INPUT";
        /** ErrorDetail */
        ErrorDetail: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
            /** Action */
            action: string;
            /** Job Id */
            job_id?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
            /** Request Id */
            request_id: string;
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /** Shot Id */
            shot_id: string;
            /** Criterion Id */
            criterion_id: string;
            /** Clip Id */
            clip_id: string;
            /** Rendition Id */
            rendition_id: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "supports" | "defect" | "uncertain";
            /** Reason */
            reason: string;
            /**
             * Continuous
             * @default false
             */
            continuous: boolean;
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Model Mode */
            model_mode: string;
            /** Worker */
            worker: string;
            /** Database */
            database: string;
        };
        /** ImportBatch */
        ImportBatch: {
            /** Revision */
            revision: number;
            /** Items */
            items: components["schemas"]["ImportItem"][];
        };
        /** ImportItem */
        ImportItem: {
            /** Filename */
            filename: string;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "duplicate" | "failed";
            /** Clip Id */
            clip_id?: string | null;
            /** Job Id */
            job_id?: string | null;
            error?: components["schemas"]["ErrorDetail"] | null;
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string | null;
            /** Kind */
            kind: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "retry_wait" | "succeeded" | "failed" | "cancelled";
            /** Attempt */
            attempt: number;
            error?: components["schemas"]["ErrorDetail"] | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
        };
        /** MembershipEdit */
        MembershipEdit: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * Membership
             * @enum {string}
             */
            membership: "included" | "excluded";
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** NextAction */
        NextAction: {
            /** Project Revision */
            project_revision: number;
            /** Shot Id */
            shot_id: string;
            /** What */
            what: string;
            /** How */
            how: string;
            /** Why */
            why: string;
        };
        /** PlanEdit */
        PlanEdit: {
            /** Expected Revision */
            expected_revision: number;
            /** Shots */
            shots: components["schemas"]["Shot"][];
        };
        /** Project */
        Project: {
            /**
             * Model Upload Consent
             * @default false
             */
            model_upload_consent: boolean;
            /** Id */
            id: string;
            /** Goal */
            goal: string;
            /** Target Seconds */
            target_seconds: number;
            /** Conditions */
            conditions: string;
            /** Revision */
            revision: number;
            /** Plan Version */
            plan_version: number;
            /** Confirmed */
            confirmed: boolean;
            /** Shots */
            shots: components["schemas"]["Shot"][];
            /** Created At */
            created_at: number;
        };
        /** ProjectPage */
        ProjectPage: {
            /** Items */
            items: components["schemas"]["Project"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Retry */
        Retry: {
            /** Expected Attempt */
            expected_attempt: number;
        };
        /** Revision */
        Revision: {
            /** Expected Revision */
            expected_revision: number;
        };
        /** Shot */
        Shot: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /**
             * Critical
             * @default false
             */
            critical: boolean;
            /** Criteria */
            criteria: components["schemas"]["Criterion"][];
        };
        /** ShotCoverage */
        ShotCoverage: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Required */
            required: boolean;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "covered" | "reshoot" | "uncertain";
            /** Evidence Ids */
            evidence_ids: string[];
            /** Missing */
            missing: string[];
        };
        /** Snapshot */
        Snapshot: {
            project: components["schemas"]["Project"];
            /** Project Id */
            project_id: string;
            /** Revision */
            revision: number;
            /** Plan Version */
            plan_version: number;
            /**
             * Model Mode
             * @enum {string}
             */
            model_mode: "simulator" | "qwen" | "unconfigured";
            /** Pipeline */
            pipeline: {
                [key: string]: number;
            };
            /** Clips */
            clips: components["schemas"]["Clip"][];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Shots */
            shots: components["schemas"]["ShotCoverage"][];
            /** Coverage Complete */
            coverage_complete: boolean;
            /**
             * Readiness
             * @enum {string}
             */
            readiness: "not_ready" | "checking" | "ready";
            /** Checked At */
            checked_at: number | null;
            next_action: components["schemas"]["NextAction"] | null;
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    projects_api_v1_projects_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProject"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generate_api_v1_projects__pid__plan_generate_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Revision"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    edit_plan_api_v1_projects__pid__plan_patch: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirm_api_v1_projects__pid__plan_confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Revision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    authorize_analysis_api_v1_projects__pid__analysis_authorize_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Revision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    snapshot_api_v1_projects__pid__snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    clips_api_v1_projects__pid__clips_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipPage"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    clip_api_v1_clips__cid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Clip"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    membership_api_v1_projects__pid__clips__cid__membership_patch: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                pid: string;
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    job_api_v1_jobs__jid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retry_api_v1_jobs__jid__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                jid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Retry"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    content_api_v1_renditions__rid__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_api_v1_projects__pid__imports_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v1_projects__pid__imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatch"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
