import { test, expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import path from 'node:path';

test('UI01–UI06 / E01–E05: create, select, reshoot, ready, playback, exclusion and refresh', async ({page}) => {
  await page.goto('/');
  await expect(page.getByText('模拟相机 · 模拟模型')).toBeVisible();
  await page.getByLabel('教程主题').fill('安装自行车支架');
  await page.getByLabel('拍摄条件').fill('室内桌面，保持连接处无遮挡');
  await page.getByRole('button', {name:'创建项目并生成分镜 →'}).click();
  await expect(page.getByRole('button',{name:'确认并锁定清单 →'})).toBeEnabled();
  await page.getByRole('button',{name:'确认并锁定清单 →'}).click();
  await page.getByRole('button',{name:'连接并浏览素材'}).click();
  await page.getByLabel(/模拟素材 · materials/).check();
  await page.getByLabel(/模拟素材 · result/).check();
  await page.getByRole('button',{name:'导入 2 组并开始同步'}).click();
  await expect(page.locator('.clip')).toHaveCount(2);
  await expect(page.locator('.badge').filter({hasText:'已覆盖'})).toHaveCount(2, {timeout:20000});
  const root = path.resolve('..');
  const add = (scenario:string) => execFileSync(path.join(root,'.venv/bin/python'), ['-m','tools.simulator','add','--scenario',scenario], {cwd:root,env:process.env});
  add('occluded');
  await expect(page.getByText('需补拍', {exact:true})).toBeVisible({timeout:20000});
  await expect(page.locator('.why')).toContainText('手遮挡');
  add('clear');
  await expect(page.getByText('已拍够', {exact:true})).toBeVisible({timeout:20000});
  await page.getByRole('button',{name:/支持证据/}).first().click();
  await expect(page.locator('video')).toBeVisible();
  await expect.poll(() => page.locator('video').evaluate((v:HTMLVideoElement) => v.readyState)).toBeGreaterThan(0);
  await page.screenshot({path:path.join(root,'test-results/workspace.png'),fullPage:true});
  await page.getByRole('button',{name:'暂停同步',exact:true}).click();
  await expect(page.getByText('覆盖齐全 · 最新素材未核验',{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.locator('.badge').filter({hasText:'已覆盖'})).toHaveCount(3);
  await page.locator('.clip').filter({hasText:'模拟素材 · clear'}).getByRole('button',{name:'排除',exact:true}).click();
  await expect(page.getByText('还差一些镜头',{exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:/开始录制|停止录制/})).toHaveCount(0);
});
